# Generated by Django 3.1 on 2022-10-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
